version: "3.8"
services:
  app:
    build:
      args:
        user: william
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: control
    container_name: control-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - control

  db:
    image: mysql:5.7
    container_name: control-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - control

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name:  registro_pedagogico_phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 300M
    restart: always
    networks:
      - control
    ports:
      - "9001:80"

  nginx:
    image: nginx:alpine
    container_name: control-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - control

networks:
  control:
    driver: bridge